# Generated by Django 3.2.16 on 2022-10-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0034_remove_pagecontent_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='text_text', serialize=False, to='cms.cmsplugin')),
                ('body', models.TextField()),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
