# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 12:40
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning', '0003_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='label',
        ),
        migrations.AddField(
            model_name='version',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], default='draft', max_length=50, protected=True),
        ),
    ]
