# Generated by Django 1.11.14 on 2018-08-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("djangocms_versioning", "0005_remove_version_label"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="version", unique_together={("content_type", "object_id")}
        )
    ]
