# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning', '0010_version_proxies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
