# Generated by Django 1.11 on 2018-10-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djangocms_versioning", "0012_create_version_numbers")]

    operations = [
        migrations.AlterField(
            model_name="version", name="number", field=models.CharField(max_length=11, verbose_name="#",)
        )
    ]
