# Generated by Django 5.2.4 on 2025-07-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning', '0017_merge_20230514_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': (('delete_versionlock', 'Can unlock version'),)},
        ),
    ]
