# Generated by Django 4.1.7 on 2023-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning', '0017_merge_20230514_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='visibility_end',
            field=models.DateTimeField(blank=True, default=None, help_text='Leave empty for unrestricted public visibility', null=True, verbose_name='visible until'),
        ),
        migrations.AddField(
            model_name='version',
            name='visibility_start',
            field=models.DateTimeField(blank=True, default=None, help_text='Leave empty for immediate public visibility', null=True, verbose_name='visible after'),
        ),
    ]
