# Generated by Django 4.1.3 on 2022-11-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
